"""empty message

Revision ID: de47442f0e61
Revises: 30d9a38e53d3
Create Date: 2025-08-09 19:08:16.518427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de47442f0e61'
down_revision: Union[str, Sequence[str], None] = '30d9a38e53d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('otps', 'user',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'otps', ['user'])
    op.create_foreign_key(None, 'otps', 'users', ['user'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'otps', type_='foreignkey')
    op.drop_constraint(None, 'otps', type_='unique')
    op.alter_column('otps', 'user',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
